# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "https://kswaste.github.io"
paginate:     1

# About/contact
author:
  name:       kswaste
  url:        https://kswaste.tistory.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown