# Setup
title:        kswaste's PlayGorund
tagline:      I'm hosted with GitHub Pages.
baseurl:      "https://kswaste.github.io"
paginate:     1

# About/contact
author:       kswaste
  name:       kswaste
  url:        https://kswaste.tistory.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
